# Generated by Django 4.2.16 on 2025-01-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='art',
            options={'verbose_name_plural': 'Art'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='art',
            old_name='Category',
            new_name='category',
        ),
        migrations.AddField(
            model_name='art',
            name='colors',
            field=models.TextField(default='Colours used to be specified'),
            preserve_default=False,
        ),
    ]
