# Generated by Django 4.2.16 on 2025-01-20 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_alter_art_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='art',
            old_name='colors',
            new_name='color',
        ),
    ]
