# Generated by Django 4.2.16 on 2025-01-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_rename_colors_art_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='price',
            field=models.IntegerField(max_length=5),
        ),
    ]
