# Generated by Django 4.2.16 on 2025-01-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_alter_art_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='art',
            name='image_2_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='art',
            name='price',
            field=models.IntegerField(),
        ),
    ]
