# Generated by Django 4.2.16 on 2025-01-23 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0005_art_image_2_art_image_2_url_alter_art_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('format', models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical'), ('square', 'Square')], max_length=25)),
                ('size', models.CharField(choices=[('140x140cm', '140x140cm'), ('100x200cm', '100x200cm'), ('100x150cm', '100x150cm')], max_length=25)),
                ('art', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='art.art')),
            ],
        ),
    ]
