# Generated by Django 4.2.16 on 2025-01-23 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0006_specification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='name',
        ),
    ]
