# Generated by Django 4.2.16 on 2025-01-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0007_remove_specification_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='orientation',
            field=models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical'), ('square', 'Square')], default='square', max_length=25),
        ),
        migrations.AddField(
            model_name='art',
            name='size',
            field=models.CharField(choices=[('140x140cm', '140x140cm'), ('100x200cm', '100x200cm'), ('100x150cm', '100x150cm')], default='140x140cm', max_length=25),
        ),
        migrations.DeleteModel(
            name='Specification',
        ),
    ]
