# Generated by Django 4.2.16 on 2025-02-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0009_art_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
