# Generated by Django 4.2.16 on 2025-02-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0011_art_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
