# Generated by Django 4.2.16 on 2025-02-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0011_alter_art_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='date',
            field=models.DateField(),
        ),
    ]
