# Generated by Django 4.2.16 on 2025-02-22 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0013_alter_art_image_alter_art_image_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='image_2_url',
        ),
        migrations.RemoveField(
            model_name='art',
            name='image_url',
        ),
    ]
