# Generated by Django 4.2.16 on 2025-02-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0014_remove_art_image_2_url_remove_art_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='date',
            field=models.DateField(help_text='Format: DD/MM/YYYY'),
        ),
    ]
