# Generated by Django 4.2.16 on 2025-02-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0015_alter_art_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='date',
            field=models.DateField(help_text='Format: YYYY-MM-DD'),
        ),
    ]
